name: sol-test-js
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Default Test
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: EthereumRemix/ts-sol-test@v1.3
        with:
          test-path: 'sample/tests'
          contract-path: 'sample/contracts'
          compiler-version: '0.8.7'
      - name: Run Custom Fork Test
        uses: EthereumRemix/ts-sol-test@v1.3
        with:
          test-path: 'sample/tests/custom/hardFork.test.ts'
          contract-path: 'sample/contracts/custom/mainnet_ens.sol'
          compiler-version: '0.8.17'
          hard-fork: 'merge'
          node-url: 'https://mainnet.infura.io/v3/08b2a484451e4635a28b3d8234f24332'

