name: sol-test-js
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run SUT Action
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: EthereumRemix/ts-sol-test@v1.3.33-dev
        with:
          test-path: 'sample/tests'
          contract-path: 'sample/contracts'
          compiler-version: '0.8.17'
          hard-fork: 'merge'
          node-url: 'https://rpc.archivenode.io/e50zmkroshle2e2e50zm0044i7ao04ym'

