name: sol-test-js
on: [push]

jobs:
  run_sample_test_job:
    runs-on: ubuntu-latest
    name: A job to run solidity tests in js
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run SUT Action
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        uses: EthereumRemix/ts-sol-test@v1.3.24-dev
        with:
          test-path: 'sample/tests'
          contract-path: 'sample/contracts'
          compiler-version: '0.8.7'
